package com.example.fooddeliveryapp.utils

const val ADDRESS_ID = "addressId"
const val CREDIT_CARD_ID = "creditCardId"
const val HOME = "Home"
const val WORK = "Work"
const val OTHER = "Other"
const val SELECT_LABEL = "Select Label (Home, Work, Other)"
const val FILL_FIELDS = "Fill All Fields"
const val ENTER_A_VALID_EMAIL = "Enter a valid Email"
const val CORRECT_CODE = "Correct Code!"
const val WRONG_CODE = "Wrong Code"
const val CODE_SENT_TO = "Code sent to"
const val NEW_CODE_SENT_TO = "New code sent to"
const val REGISTRATION_COMPLETE = "Registration Complete!"
const val THE_PASSWORD_DO_NOT_MATCHES = "The passwords do not matches"
const val PLEASE_FILL = "Please fill in all registration fields"
const val ONGOING = "Ongoing"
const val HISTORY = "History"
const val FOOD_PREFS = "Food_prefs"
const val REMEMBER_ME = "rememberME"
const val WRONG_EMAIL_PSW = "Wrong Email o Password"
const val COUPON_DIALOG = "CouponDialog"
const val FILTER_DIALOG = "FilterDialog"
const val ADDRESSES = "addresses"
const val CREDIT_CARDS = "credit_cards"
const val FOOD_DELIVERY_DB = "food_delivery_db"
const val NO_ADDRESS_INSERTED = "No address inserted"
const val VISA = "VISA"
const val MASTERCARD = "MASTERCARD"
const val VISA_CAMELCASE = "Visa"
const val MASTERCARD_CAMELCASE = "Mastercard"
const val FB_LOGIN = "FBLogin"
const val LOGIN_SUCCESS = "Login success:"
const val LOGIN_CANCELED = "Login canceled:"
const val LOGIN_ERROR = "Login error:"
const val EMAIL = "email"
const val ERROR_FACEBOOK = "Error parsing Facebook user data"
const val ERROR_TWITTER = "Error parsing Twitter user data"
const val NO_EMAIL = "No email available"
const val PAYMENT_FAILED = "Payment failed try again!"
const val ERROR = "Error"
const val TRY_AGAIN = "Try Again"
const val FIELDS = "fields"
const val ID_NAME_EMAIL = "id,name,email"
const val PUBLIC_PROFILE = "public_profile"
const val REGISTER_FAILED = "Register failed:"
const val PAYMENT_SUCCESS = "payment_success"
const val PAYMENT_CANCEL = "payment_cancel"
const val TWITTER_COM = "twitter.com"
const val URL = "url"
const val INITIAL_POSITION = "Initial Position"
const val CATEGORY_REQUEST_KEY = "categoryRequestKey"
const val SELECTED_CATEGORY = "selectedCategory"
const val FILTER_REQUEST_KEY = "filterRequestKey"
const val DELIVERY_TIME_RANGE = "deliveryTimeRange"
const val PRICING_RANGE = "pricingRange"
const val MIN_RATING = "minRating"
const val USER_SELECTED = "UserSelected"




